feat[Hillel-2]: DB host to localhost

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,13 +31,11 @@ jobs:
         runs-on: ubuntu-latest
         services:
             postgres: 
-                image: postgres:latest
+                image: postgres:16-alpine
                 env:
-                    PG_NAME: test_db
-                    PG_USER: test_user
-                    PG_PASSWORD: test_password
-                    PG_HOST: postgres
-                    PG_PORT: 5432
+                    POSTGRES_DB: test_db
+                    POSTGRES_USER: test_user
+                    POSTGRES_PASSWORD: test_password
                 ports:
                     - 5432:5432
 
@@ -55,6 +53,14 @@ jobs:
                 python -m pip install --upgrade pip
                 pip install -r requirements.txt
             
+            - name: PSQL test
+              if: failure()
+              run: |
+                nc -zv localhost 5432
+                psql - h localhost -U postgres -c "SELECT version();" 2>&1 || echo "Connection failed"
+              env:
+                POSTGRES_PASSWORD: test_password
+
             - name: Run migrations
               run: python manage.py migrate
               env:
